# Generated by Django 2.2.2 on 2019-06-19 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='summary',
            name='amount',
            field=models.IntegerField(default=0, max_length=5),
        ),
        migrations.AddField(
            model_name='summary',
            name='working',
            field=models.IntegerField(default=0, max_length=10),
        ),
    ]
